Add the 0b1010 commandments
kennethlove/code-scripture pull request #1
Opened 2017-02-25 04:36 UTC by mattjegan

2017-02-25 15:47 UTC, kennethlove requested changes
Can you swap the "You"s with "Thou"s, etc?

2017-02-25 15:47 UTC, kennethlove commented on scripture.txt
> +You shall have no other branchs before Master.
spelling, should be "branches"

2017-02-25 15:47 UTC, kennethlove commented on scripture.txt
> +You shall not take the name of the Linus your BDFL in vain.
I'd rather not name individuals (also Linus isn't a good tech person).

2017-02-25 23:28 UTC, mattjegan commented
No worries, made the changes and updated "your" to "thy" as well.

2017-08-01 04:08 UTC, mattjegan commented
@kennethlove could we get this merged?

2017-08-10 23:58 UTC, merged

2017-08-11 00:05 UTC, mattjegan commented
Cheers 👍